import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "../lib/api";

interface IPost {
  id: number;
  title: string;
  description: string;
  content: string;
  image: string;
  imageSrc: string;
}

interface IProps {
  title: string;
  post: IPost;
}

const myLoader = ({ src }: any) => {
  return src;
};

const PostPage: NextPage<IProps> = ({ title, post }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <img
          src="http://113.30.190.164:5000/a1a2ad8c-b3af-4992-b529-bc8296a3a4d7.jpg"
          alt="no https"
          className="w-2/3"
        />
        <Image
          loader={myLoader}
          src={post.imageSrc}
          alt={post.title}
          width={500}
          height={500}
        />
        <h1>{post.title}</h1>
        <h3>{post.imageSrc}</h3>
        <h5>{post.description}</h5>
        <p>{post.content}</p>
      </main>
    </>
  );
};

PostPage.getInitialProps = async ({ req, query }) => {
  const title = query.title as string;
  const data = await api.post(req, title);
  return { ...data, title };
};

export default PostPage;
