import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "../lib/api";
import Link from "next/link";

interface IPost {
  id: number;
  title: string;
  description: string;
  content: string;
  image: string;
  userId: number;
  categoryId: number;
  createdAt: Date;
  updatedAt: Date;
  imageSrc: string;
}

interface IProps {
  title: string;
  post: IPost;
}

const myLoader = ({ src }: any) => src;

const PostPage: NextPage<IProps> = ({ title, post }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          loader={myLoader}
          src={post.imageSrc}
          alt={post.title}
          width={50}
          height={50}
          unoptimized={true}
        />
        <h1>{post.title}</h1>
        <h5>{post.description}</h5>
        <p>{post.content}</p>
        <Link href={`categories/${post.categoryId}`}>
          <a className="bg-black text-gray-400">
            <p>#CATEGORY</p>
          </a>
        </Link>
      </main>
    </>
  );
};

PostPage.getInitialProps = async ({ req, query }) => {
  const title = query.title as string;
  const data = await api.post(req, title);
  return { ...data, title };
};

export default PostPage;
